version: '3'

services:
  api:
    build: ./
    image: pr-api
    container_name: api
    command: node_modules/nodemon/bin/nodemon.js -r esm prApi.js
    volumes:
      - ./:/code/
    ports:
      - "3000:3000"

  pr-redis:
    container_name: pr-redis
    image: redis

  pr-postgres:
    container_name: pr-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: pr
      POSTGRES_PASSWORD: prapi
    ports:
      - "5433:5432"
    volumes:
      - "./initDB/prPostgres:/docker-entrypoint-initdb.d"
